language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ng-cordova' ]; then cd .. && eval "mv $currentfolder generator-ng-cordova" && cd generator-ng-cordova; fi

